export const ARK_EXM_CONTRACT = "Z7JzRRt2iTQWV5LziNhTV6SP51tVKkCf_qrUqtlwzpg";

export const ARK_ETHEREUM_CONTRACT = "0xdE44d3fB118E0f007f2C0D8fFFE98b994383949A"

export const ARK_OPTIMISM_CONTRACT = ARK_ETHEREUM_CONTRACT;
export const ARK_BINANCE_CONTRACT = ARK_ETHEREUM_CONTRACT;
export const ARK_POLYGON_CONTRACT = ARK_ETHEREUM_CONTRACT;
export const ARK_FANTOM_CONTRACT = ARK_ETHEREUM_CONTRACT;
export const ARK_EVMOS_CONTRACT = ARK_ETHEREUM_CONTRACT;
export const ARK_ARBITRUM_CONTRACT = ARK_ETHEREUM_CONTRACT;


export const EVM_ORACLES = {
  1: ARK_ETHEREUM_CONTRACT,
  10: ARK_OPTIMISM_CONTRACT,
  56: ARK_BINANCE_CONTRACT,
  137: ARK_ETHEREUM_CONTRACT,
  250: ARK_ETHEREUM_CONTRACT,
  9001: ARK_ETHEREUM_CONTRACT,
  42161: ARK_ETHEREUM_CONTRACT,
};

export const ARK_NEAR_CONTRACT = "ark_station_1.near";
